// NearbyData.js
import { CheckBadgeIcon } from "react-native-heroicons/solid";
import {
    user1,
    user2,
    user3,
    user4,
    user5,
    user6,
    user7,
    user8,
    user9,
  } from "../assets/images";

export const nearbyUsers = [
    {
      id: 1,
      name: "Peggie",
      age: 28,
      hobbies: ["Concerts", "Festivals", "Photography"],
      bio: "Hey there! My name is Peggie. I'm a passionate fashion photographer with a love for capturing the beauty in everyday life...",
      distance: "3 miles away",
      imgPath: user1,
      gallery: [
        "https://randomuser.me/api/portraits/women/52.jpg",
        "https://randomuser.me/api/portraits/women/53.jpg",
        "https://randomuser.me/api/portraits/women/54.jpg",
        "https://randomuser.me/api/portraits/women/55.jpg",
      ],
      location: 'Kwara Ilorin',
      isOnline: true,
      lastMessage: "Hi! How are you?",
      timeSent: "4:00 PM",
      status: "online",
      notifications: [
        { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
      ],
      statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,  // Use the correct color from your `colors` module
      workExperience: 'Business',
      education: 'Education',
      jobTitle: 'Fashion Photographer',
      interests: ['Travel', 'Photography', 'Cooking'],
      socialMedia: [
        { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
        { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
        { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
      ],
    },
    {
      id: 2,
      name: "Diana",
      age: 30,
      hobbies: ["Hiking", "Cooking", "Music"],
      bio: "Hi there! I'm Diana, a nature lover who finds joy in the kitchen and the magic of music. Let's go on a hike and then cook up a storm together.",
      distance: "10 miles away",
      imgPath: user2,
      gallery: [
        "https://randomuser.me/api/portraits/women/60.jpg",
        "https://randomuser.me/api/portraits/women/61.jpg",
        "https://randomuser.me/api/portraits/women/62.jpg",
        "https://randomuser.me/api/portraits/women/62.jpg",
      ],
      location: 'Kwara Ilorin',
      isOnline: true,
      lastMessage: "Hi! How are you?",
      timeSent: "4:00 PM",
      status: "online",
      notifications: [
        { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
      ],
      statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
      workExperience: 'Business',
      education: 'Education',
      jobTitle: 'Fashion Photographer',
      interests: ['Travel', 'Photography', 'Cooking'],
      socialMedia: [
        { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
        { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
        { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
      ],
    },
    {
      id: 3,
      name: "Sophie",
      age: 26,
      hobbies: ["Painting", "Yoga", "Traveling"],
      bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
      distance: "2 miles away",
      imgPath: user3,
      gallery: [
        "https://randomuser.me/api/portraits/women/42.jpg",
        "https://randomuser.me/api/portraits/women/42.jpg",
        "https://randomuser.me/api/portraits/women/42.jpg",
        "https://randomuser.me/api/portraits/women/42.jpg",
      ],
      location: 'Kwara Ilorin',
      isOnline: true,
      lastMessage: "Hi! How are you?",
      timeSent: "4:00 PM",
      status: "online",
      notifications: [
        { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
      ],
      statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
      workExperience: 'Business',
      education: 'Education',
      jobTitle: 'Fashion Photographer',
      interests: ['Travel', 'Photography', 'Cooking'],
      socialMedia: [
        { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
        { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
        { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
      ],
    },
    {
        id: 4,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user4,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 5,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user5,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
    // Add more profiles as needed
    {
        id: 6,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user6,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 7,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user7,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 8,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user8,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 9,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user9,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 10,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user3,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 11,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user5,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 12,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user1,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 13,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user8,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 14,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user2,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 15,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imgPath: user4,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
  ];
  