// NearbyData.js
import { CheckBadgeIcon } from "react-native-heroicons/solid";
import {
    user1,
    user2,
    user3,
    user4,
    user5,
    user6,
    user7,
    user8,
    user9,
    user10,
    user11,
    user12,
    user13,
    user14,
    user15,
    user16,
    user17,
    user18,
    user19,
    user20,
    user21,
    user22,
    user23,
    user24,
    user25,
    user26,
    user27,
    user28,
    user29,
    user30,
    user31,
    user32,
    user33,
    user34,
    user35,
    user36,
    user37,
    user38,
    user39,
    user40,
    user41,
    user42,
  user43,
  user44,
  user45,
  user46,
  user47,
  user48,
  user49,
  user50,
  user51,
  user52,
  user53,
  user54,
  } from "../assets/images";

export const nearbyUsers = [
    {
      id: 1,
      name: "Peggie",
      age: 28,
      hobbies: ["Concerts", "Festivals", "Photography"],
      bio: "Hey there! My name is Peggie. I'm a passionate fashion photographer with a love for capturing the beauty in everyday life...",
      distance: "3 miles away",
      imageUrl: user1,
      gallery: [
        "https://randomuser.me/api/portraits/women/52.jpg",
        "https://randomuser.me/api/portraits/women/53.jpg",
        "https://randomuser.me/api/portraits/women/54.jpg",
        "https://randomuser.me/api/portraits/women/55.jpg",
      ],
      location: 'Kwara Ilorin',
      isOnline: true,
      lastMessage: "Hi! How are you?",
      timeSent: "4:00 PM",
      status: "online",
      height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'Non-smoker',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
      statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,  // Use the correct color from your `colors` module
      workExperience: 'Business',
      education: 'High school',
      jobTitle: 'Fashion Photographer',
      interests: ['Travel', 'Photography', 'Cooking'],
      socialMedia: [
        { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
        { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
        { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
      ],
    },
    {
      id: 2,
      name: "Diana",
      age: 30,
      hobbies: ["Hiking", "Cooking", "Music"],
      bio: "Hi there! I'm Diana, a nature lover who finds joy in the kitchen and the magic of music. Let's go on a hike and then cook up a storm together.",
      distance: "10 miles away",
      imageUrl: user2,
      gallery: [
        "https://randomuser.me/api/portraits/women/60.jpg",
        "https://randomuser.me/api/portraits/women/61.jpg",
        "https://randomuser.me/api/portraits/women/62.jpg",
        "https://randomuser.me/api/portraits/women/62.jpg",
      ],
      location: 'Kwara Ilorin',
      isOnline: true,
      lastMessage: "Hi! How are you?",
      timeSent: "4:00 PM",
      status: "online",
      height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
      notifications: [
        { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
      ],
      statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
      workExperience: 'Business',
      education: 'Education',
      jobTitle: 'Fashion Photographer',
      interests: ['Travel', 'Photography', 'Cooking'],
      socialMedia: [
        { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
        { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
        { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
      ],
    },
    {
      id: 3,
      name: "Sophie",
      age: 26,
      hobbies: ["Painting", "Yoga", "Traveling"],
      bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
      distance: "2 miles away",
      imageUrl: user3,
      gallery: [
        "https://randomuser.me/api/portraits/women/42.jpg",
        "https://randomuser.me/api/portraits/women/42.jpg",
        "https://randomuser.me/api/portraits/women/42.jpg",
        "https://randomuser.me/api/portraits/women/42.jpg",
      ],
      location: 'Kwara Ilorin',
      isOnline: true,
      lastMessage: "Hi! How are you?",
      timeSent: "4:00 PM",
      status: "online",
      height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
      notifications: [
        { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
      ],
      statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
      workExperience: 'Business',
      education: 'Education',
      jobTitle: 'Fashion Photographer',
      interests: ['Travel', 'Photography', 'Cooking'],
      socialMedia: [
        { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
        { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
        { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
      ],
    },
    {
        id: 4,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user4,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 5,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user5,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
    // Add more profiles as needed
    {
        id: 6,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user6,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 7,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user7,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 8,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user8,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 9,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user9,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 10,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user10,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 11,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user11,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 12,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user12,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 13,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user13,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 14,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user14,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 15,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user15,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 16,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user16,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 17,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user17,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 18,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user18,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 19,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user19,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 20,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user20,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 21,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user21,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 22,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user22,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 23,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user23,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 24,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user24,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 25,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user25,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 26,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user26,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 27,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user27,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 28,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user28,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 29,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user29,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 30,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user30,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 31,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user31,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 32,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user32,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 33,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user33,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 34,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user34,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 35,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user35,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 36,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user36,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 37,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user37,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 38,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user38,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 39,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user39,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 40,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user40,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 41,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user41,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 42,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user43,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 44,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user44,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 45,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user45,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 46,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user46,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 47,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user47,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 48,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user48,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 49,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user49,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 50,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user50,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 51,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user51,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 52,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user52,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 53,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user53,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 54,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user54,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
      {
        id: 54,
        name: "Sophie",
        age: 26,
        hobbies: ["Painting", "Yoga", "Traveling"],
        bio: "Greetings! I'm Sophie, a free-spirited artist who finds inspiration in the colors of life. Yoga keeps me grounded, and painting allows my imagination to soar.",
        distance: "2 miles away",
        imageUrl: user42,
        gallery: [
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
          "https://randomuser.me/api/portraits/women/42.jpg",
        ],
        location: 'Kwara Ilorin',
        isOnline: true,
        lastMessage: "Hi! How are you?",
        timeSent: "4:00 PM",
        status: "online",
        height: '50cm',
      kids: 'Already have',
      drinking: 'Never',
      language: ['English', 'Yoruba'],
      relationship: 'Single',
      sexuality: 'Straight',
      smoking: 'No',
      starSign: 'Scorpio',
      pets: 'No pets',
      religion: 'Christian',
      personality: 'Somewhere in between',
        notifications: [
          { id: 1, message: "Hi! How are you?", timestamp: "4:00 PM" }
        ],
        statusIcon: <CheckBadgeIcon size={24} color="#00FF00" />,
        workExperience: 'Business',
        education: 'Education',
        jobTitle: 'Fashion Photographer',
        interests: ['Travel', 'Photography', 'Cooking'],
        socialMedia: [
          { platform: "Instagram", profileLink: "https://www.instagram.com/diana_sullivan/" },
          { platform: "Snapchat", profileLink: "https://www.snapchat.com/add/diana_sullivan" },
          { platform: "Facebook", profileLink: "https://www.facebook.com/diana.sullivan" },
        ],
      },
  ];
  